// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: Candidate.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CandidateServiceClient is the client API for CandidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandidateServiceClient interface {
	CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error)
	GetAllCandidates(ctx context.Context, in *Candidate_Void, opts ...grpc.CallOption) (*GetAllCandidatesResponse, error)
	GetByIdCandidate(ctx context.Context, in *GetByIdCandidateRequest, opts ...grpc.CallOption) (*GetByIdCandidateResponse, error)
	UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error)
	DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error)
}

type candidateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandidateServiceClient(cc grpc.ClientConnInterface) CandidateServiceClient {
	return &candidateServiceClient{cc}
}

func (c *candidateServiceClient) CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error) {
	out := new(Candidate_Void)
	err := c.cc.Invoke(ctx, "/voting.CandidateService/CreateCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) GetAllCandidates(ctx context.Context, in *Candidate_Void, opts ...grpc.CallOption) (*GetAllCandidatesResponse, error) {
	out := new(GetAllCandidatesResponse)
	err := c.cc.Invoke(ctx, "/voting.CandidateService/GetAllCandidates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) GetByIdCandidate(ctx context.Context, in *GetByIdCandidateRequest, opts ...grpc.CallOption) (*GetByIdCandidateResponse, error) {
	out := new(GetByIdCandidateResponse)
	err := c.cc.Invoke(ctx, "/voting.CandidateService/GetByIdCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) UpdateCandidate(ctx context.Context, in *UpdateCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error) {
	out := new(Candidate_Void)
	err := c.cc.Invoke(ctx, "/voting.CandidateService/UpdateCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*Candidate_Void, error) {
	out := new(Candidate_Void)
	err := c.cc.Invoke(ctx, "/voting.CandidateService/DeleteCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateServiceServer is the server API for CandidateService service.
// All implementations must embed UnimplementedCandidateServiceServer
// for forward compatibility
type CandidateServiceServer interface {
	CreateCandidate(context.Context, *CreateCandidateRequest) (*Candidate_Void, error)
	GetAllCandidates(context.Context, *Candidate_Void) (*GetAllCandidatesResponse, error)
	GetByIdCandidate(context.Context, *GetByIdCandidateRequest) (*GetByIdCandidateResponse, error)
	UpdateCandidate(context.Context, *UpdateCandidateRequest) (*Candidate_Void, error)
	DeleteCandidate(context.Context, *DeleteCandidateRequest) (*Candidate_Void, error)
	mustEmbedUnimplementedCandidateServiceServer()
}

// UnimplementedCandidateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCandidateServiceServer struct {
}

func (UnimplementedCandidateServiceServer) CreateCandidate(context.Context, *CreateCandidateRequest) (*Candidate_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) GetAllCandidates(context.Context, *Candidate_Void) (*GetAllCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCandidates not implemented")
}
func (UnimplementedCandidateServiceServer) GetByIdCandidate(context.Context, *GetByIdCandidateRequest) (*GetByIdCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) UpdateCandidate(context.Context, *UpdateCandidateRequest) (*Candidate_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) DeleteCandidate(context.Context, *DeleteCandidateRequest) (*Candidate_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) mustEmbedUnimplementedCandidateServiceServer() {}

// UnsafeCandidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandidateServiceServer will
// result in compilation errors.
type UnsafeCandidateServiceServer interface {
	mustEmbedUnimplementedCandidateServiceServer()
}

func RegisterCandidateServiceServer(s grpc.ServiceRegistrar, srv CandidateServiceServer) {
	s.RegisterService(&CandidateService_ServiceDesc, srv)
}

func _CandidateService_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.CandidateService/CreateCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, req.(*CreateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_GetAllCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Candidate_Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetAllCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.CandidateService/GetAllCandidates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetAllCandidates(ctx, req.(*Candidate_Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_GetByIdCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetByIdCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.CandidateService/GetByIdCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetByIdCandidate(ctx, req.(*GetByIdCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_UpdateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).UpdateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.CandidateService/UpdateCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).UpdateCandidate(ctx, req.(*UpdateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.CandidateService/DeleteCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).DeleteCandidate(ctx, req.(*DeleteCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CandidateService_ServiceDesc is the grpc.ServiceDesc for CandidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voting.CandidateService",
	HandlerType: (*CandidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCandidate",
			Handler:    _CandidateService_CreateCandidate_Handler,
		},
		{
			MethodName: "GetAllCandidates",
			Handler:    _CandidateService_GetAllCandidates_Handler,
		},
		{
			MethodName: "GetByIdCandidate",
			Handler:    _CandidateService_GetByIdCandidate_Handler,
		},
		{
			MethodName: "UpdateCandidate",
			Handler:    _CandidateService_UpdateCandidate_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _CandidateService_DeleteCandidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Candidate.proto",
}
