// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: Vote.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoteServiceClient is the client API for VoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteServiceClient interface {
	CreateVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote_Void, error)
	GetAllVote(ctx context.Context, in *Vote_Void, opts ...grpc.CallOption) (*GetAllVotes, error)
	GetByIdVote(ctx context.Context, in *GetVoteRequest, opts ...grpc.CallOption) (*Vote, error)
	UpdateVote(ctx context.Context, in *UpdateVoteRequest, opts ...grpc.CallOption) (*Vote_Void, error)
	DeleteVote(ctx context.Context, in *DeleteVoteRequest, opts ...grpc.CallOption) (*Vote_Void, error)
}

type voteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteServiceClient(cc grpc.ClientConnInterface) VoteServiceClient {
	return &voteServiceClient{cc}
}

func (c *voteServiceClient) CreateVote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote_Void, error) {
	out := new(Vote_Void)
	err := c.cc.Invoke(ctx, "/voting.VoteService/CreateVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) GetAllVote(ctx context.Context, in *Vote_Void, opts ...grpc.CallOption) (*GetAllVotes, error) {
	out := new(GetAllVotes)
	err := c.cc.Invoke(ctx, "/voting.VoteService/GetAllVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) GetByIdVote(ctx context.Context, in *GetVoteRequest, opts ...grpc.CallOption) (*Vote, error) {
	out := new(Vote)
	err := c.cc.Invoke(ctx, "/voting.VoteService/GetByIdVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) UpdateVote(ctx context.Context, in *UpdateVoteRequest, opts ...grpc.CallOption) (*Vote_Void, error) {
	out := new(Vote_Void)
	err := c.cc.Invoke(ctx, "/voting.VoteService/UpdateVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) DeleteVote(ctx context.Context, in *DeleteVoteRequest, opts ...grpc.CallOption) (*Vote_Void, error) {
	out := new(Vote_Void)
	err := c.cc.Invoke(ctx, "/voting.VoteService/DeleteVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServiceServer is the server API for VoteService service.
// All implementations must embed UnimplementedVoteServiceServer
// for forward compatibility
type VoteServiceServer interface {
	CreateVote(context.Context, *Vote) (*Vote_Void, error)
	GetAllVote(context.Context, *Vote_Void) (*GetAllVotes, error)
	GetByIdVote(context.Context, *GetVoteRequest) (*Vote, error)
	UpdateVote(context.Context, *UpdateVoteRequest) (*Vote_Void, error)
	DeleteVote(context.Context, *DeleteVoteRequest) (*Vote_Void, error)
	mustEmbedUnimplementedVoteServiceServer()
}

// UnimplementedVoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoteServiceServer struct {
}

func (UnimplementedVoteServiceServer) CreateVote(context.Context, *Vote) (*Vote_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVote not implemented")
}
func (UnimplementedVoteServiceServer) GetAllVote(context.Context, *Vote_Void) (*GetAllVotes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVote not implemented")
}
func (UnimplementedVoteServiceServer) GetByIdVote(context.Context, *GetVoteRequest) (*Vote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdVote not implemented")
}
func (UnimplementedVoteServiceServer) UpdateVote(context.Context, *UpdateVoteRequest) (*Vote_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVote not implemented")
}
func (UnimplementedVoteServiceServer) DeleteVote(context.Context, *DeleteVoteRequest) (*Vote_Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVote not implemented")
}
func (UnimplementedVoteServiceServer) mustEmbedUnimplementedVoteServiceServer() {}

// UnsafeVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteServiceServer will
// result in compilation errors.
type UnsafeVoteServiceServer interface {
	mustEmbedUnimplementedVoteServiceServer()
}

func RegisterVoteServiceServer(s grpc.ServiceRegistrar, srv VoteServiceServer) {
	s.RegisterService(&VoteService_ServiceDesc, srv)
}

func _VoteService_CreateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).CreateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.VoteService/CreateVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).CreateVote(ctx, req.(*Vote))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_GetAllVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote_Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).GetAllVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.VoteService/GetAllVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).GetAllVote(ctx, req.(*Vote_Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_GetByIdVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).GetByIdVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.VoteService/GetByIdVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).GetByIdVote(ctx, req.(*GetVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_UpdateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).UpdateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.VoteService/UpdateVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).UpdateVote(ctx, req.(*UpdateVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_DeleteVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).DeleteVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voting.VoteService/DeleteVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).DeleteVote(ctx, req.(*DeleteVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoteService_ServiceDesc is the grpc.ServiceDesc for VoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voting.VoteService",
	HandlerType: (*VoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVote",
			Handler:    _VoteService_CreateVote_Handler,
		},
		{
			MethodName: "GetAllVote",
			Handler:    _VoteService_GetAllVote_Handler,
		},
		{
			MethodName: "GetByIdVote",
			Handler:    _VoteService_GetByIdVote_Handler,
		},
		{
			MethodName: "UpdateVote",
			Handler:    _VoteService_UpdateVote_Handler,
		},
		{
			MethodName: "DeleteVote",
			Handler:    _VoteService_DeleteVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Vote.proto",
}
